universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include argument
arguments               = -m scripts.extract_targets --encoder siglip --split val

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/extr_targets_siglip_val.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/extr_targets_siglip_val.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/extr_targets_siglip_val.$(ClusterId).log

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 4
request_memory = 12G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1
