universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include argument
arguments               = -u -m scripts.extract_anyup_features --encoder clip --layer 3 --max_train_cached_batches 500 --max_val_cached_batches 100 --micro_batch_size 4

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/extr_feat_anyup_clip_layer3.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/extr_feat_anyup_clip_layer3.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/extr_feat_anyup_clip_layer3.$(ClusterId).log

stream_output = True
stream_error = True

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 4
request_memory = 12G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1