universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include arguments
arguments               = -u -m scripts.run_e3 --encoder siglip --target_type edges --layers 3

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/e3_edges_siglip_layer3.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/e3_edges_siglip_layer3.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/e3_edges_siglip_layer3.$(ClusterId).log

stream_output = true
stream_error = true

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 1
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1