universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include argument
arguments               = -m scripts.run_e1_e2 --encoder siglip --target_type edges --layers $(Layer)

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/e1_e2_siglip_edge.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/e1_e2_siglip_edge.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/e1_e2_siglip_edge.$(ClusterId).log

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 2
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue Layer from (
    -1
    3
    6
    9
)
