universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include arguments
arguments               = -u -m scripts.train_probes_anyup --encoder dino --target_type rgb --layers $(Layer) --max_train_cached_batches 500 --max_val_cached_batches 100

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/train_probes_anyup_dino.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/train_probes_anyup_dino.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/train_probes_anyup_dino.$(ClusterId).log

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 1
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue Layer from (
	-1
	3
	6
	9
)
