universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include argument
arguments               = -u -m scripts.train_probes --encoder siglip --target_type edges --layers $(Layer) --max_train_cached_batches 500

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/train_probe_siglip_edge.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/train_probe_siglip_edge.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/train_probe_siglip_edge.$(ClusterId).log

stream_output = True
stream_error = True

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 4
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue Layer from (
    -1
    3
    6
    9
)
