universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include argument
arguments               = -u -m scripts.train_probes --encoder dino --target_type edges --layers -1 --max_train_cached_batches 5 --max_val_cached_batches 1

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/train_probe_dino_edg_tes.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/train_probe_dino_edg_tes.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/train_probe_dino_edg_tes.$(ClusterId).log

stream_output = True
stream_error = True

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 4
request_memory = 16G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1
