universe                = docker
docker_image            = nvidia/cuda:11.4.3-runtime-ubuntu20.04
executable              = execute.sh

# Python file to run, can also include argument
arguments               = -m scripts.train_probes --encoder dino --layers -1 --target_type rgb --batch_size 64 --num_epochs 2

# Paths to output, error, and log files
# Make sure all the parent directories exist
output                  = /home/hlcv_team015/condor_logs/train_probes_debug.$(ClusterId).$(ProcId).out
error                   = /home/hlcv_team015/condor_logs/train_probes_debug.$(ClusterId).$(ProcId).err
log                     = /home/hlcv_team015/condor_logs/train_probes_debug.$(ClusterId).log

should_transfer_files   = YES

# Remove this when using interactive mode
# when_to_transfer_output = ON_EXIT

request_GPUs = 1
request_CPUs = 1
request_memory = 8G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1
