imagenet_root: /home/hlcv_team015/datasets/imagenet

cache_dir: /home/hlcv_team015/HLCVProject/cache

results_dir: /home/hlcv_team015/HLCVProject/results

checkpoints_dir: /home/hlcv_team015/HLCVProject/checkpoints